### ISSUE TITLE
Renaming of package

### ISSUE THREAD

**Issue by EmilHvitfeldt** [shandiya/feather#2]
Hello @shandiya, Love the package!

The name of the package overlaps with another commonly used package on CRAN, which can cause some issues if you want to have both installed. Would you consider renaming the package? Maybe "feathers"?

**Comment by shandiya** [comment]
Hi @EmilHvitfeldt, thanks for the feedback! I think you're right, it's for the best if I change the name. I'll get onto it  later this week.

**Comment by shandiya** [comment]
Done! Let me know if you run into any issues using it

**Comment by zkamvar** [comment]
IDK if I'm too late to suggest naming this "plumage" to strengthen the difference between the package names? From my running of [the available package](https://github.com/r-lib/available#readme), it appears that this name is up for grabs :smiley:
